hl.config({ autogenerated = false })

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output   = "",
	mode     = "preferred",
	position = "auto",
	scale    = "1.25",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- set $mod Mod4
-- set $term kitty
-- set $menu rofi -show run
local mainMod  = "SUPER"
local terminal = "kitty"
local menu     = "rofi -show run"


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- gaps outer 8 / gaps inner 4
-- for_window [class="^.*"] border pixel 2
-- client.focused #ffffff #ffffff #ffffff #ffffff




hl.config({
	general = {
		gaps_in     = 4,
		gaps_out    = 8,
		border_size = 2,

		col         = {
			active_border   = "rgba(ffffffee)",
			inactive_border = "rgba(595959aa)",
		},
		layout      = "dwindle",
	},



	decoration = {
		rounding         = 0,
		rounding_power   = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity   = 1.0,
		inactive_opacity = 1.0,

		shadow           = {
			enabled      = true,
			range        = 4,
			render_power = 3,
			color        = 0xee1a1a1a,
		},


		blur = {
			enabled           = true,
			size              = 5,
			passes            = 3,
			new_optimizations = true,
		},
	},

	animations = {
		enabled = true,
	},
})



-- 1. 定义贝塞尔曲线 (使用 hl.curve)
hl.curve("myBezier", {
	type = "bezier",
	points = { { 0.05, 0.9 }, { 0.1, 1.05 } }
})

-- 2. 开启动画全局开关 (关键修正：目标节点是 "global"！)
hl.animation({
	leaf = "global",
	enabled = true,
	speed = 10, -- 建议补上 speed 和 bezier 防止底层 C++ 报错
	bezier = "default"
})

-- 3. 配置各个具体动画节点 (严格遵循单个 table 传参，使用 bezier 字段)
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 10, bezier = "myBezier" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "myBezier", style = "slide" })


-- hl.curve("overshoot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })

-- hl.animation({ leaf = "global", enabled = true, speed = 4, bezier = "overshoot" })

-- hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "overshoot", style = "popin 87%" })
-- hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "overshoot", style = "slidefade 20%" })








hl.on("hyprland.start", function()
	hl.exec_cmd("fcitx5")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("mako")
	hl.exec_cmd("~/script/swaybg_startup.sh")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("waybar")
	hl.exec_cmd("throne")
end)

hl.on("hyprland.start", function()
	hl.exec_cmd(
		"dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland XDG_MENU_PREFIX=arch-")
end)

hl.on("hyprland.start", function()
	hl.exec_cmd("hypridle")
end)



---------------
---- INPUT ----
---------------

-- input "type:keyboard" { xkb_layout "us,ru"; xkb_options "grp:alt_space_toggle" }
-- input "type:touchpad" { tap enabled; natural_scroll enabled }
-- input "type:pointer"  { accel_profile flat; pointer_accel 0 }
hl.config({
	input = {
		kb_layout     = "us,ru",
		kb_variant    = "",
		kb_model      = "",
		kb_options    = "grp:alt_space_toggle",
		kb_rules      = "",

		sensitivity   = 0.5, -- pointer_accel 0
		accel_profile = "flat",
		touchpad      = {
			natural_scroll = true,
			tap_to_click   = true,
		},
	},
})


---------------------
---- KEYBINDINGS ----
---------------------

-- floating_modifier $mod
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- bindsym Print exec bash -c 'mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/$(date +%F_%H-%M-%S).png | wl-copy && notify-send "screenshot"'
hl.bind("Print",
	hl.dsp.exec_cmd(
		[[bash -c 'mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/$(date +%F_%H-%M-%S).png | wl-copy && notify-send "screenshot"']]))

-- clipboard
-- bindsym $mod+v exec cliphist list | rofi -dmenu -p "clipboard history" | cliphist decode | wl-copy
hl.bind(mainMod .. " + V",
	hl.dsp.exec_cmd([[cliphist list | rofi -dmenu -p "clipboard history" | cliphist decode | wl-copy]]))

-- bindsym $mod+q exec $term
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))

-- bindsym $mod+r exec $menu
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

-- bindsym Mod1+F4 kill
hl.bind("ALT + F4", hl.dsp.window.close())

-- bindsym $mod+left/down/up/right focus <dir>
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))

-- bindsym $mod+Shift+left/down/up/right move <dir>
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))

-- bindsym $mod+f fullscreen toggle
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())

-- bindsym $mod+h layout toggle split
hl.bind(mainMod .. " + H", hl.dsp.layout("togglesplit"))

-- bindsym $mod+e exec nautilus
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("nautilus"))

-- bindsym $mod+space floating toggle
hl.bind(mainMod .. " + space", hl.dsp.window.float({ action = "toggle" }))

-- bindsym $mod+a focus parent
-- hl.bind(mainMod .. " + A", hl.dsp.window.focus_parent())

hl.bind("XF86AudioRaiseVolume",
	hl.dsp.exec_cmd(
		[[wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -t 1000 "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)"%"}')"]]),
	{ locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",
	hl.dsp.exec_cmd(
		[[wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -t 1000 "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)"%"}')"]]),
	{ locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",
	hl.dsp.exec_cmd(
		[[brightnessctl s 10%+ && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -t 1000 "Brightness" "$(brightnessctl -m | awk -F, '{print $4}')"]]),
	{ locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",
	hl.dsp.exec_cmd(
		[[brightnessctl s 10%- && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -t 1000 "Brightness" "$(brightnessctl -m | awk -F, '{print $4}')"]]),
	{ locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- gamma
-- bindsym $mod+Mod1+up   exec ~/script/gamma.sh up
-- bindsym $mod+Mod1+down exec ~/script/gamma.sh down
hl.bind(mainMod .. " + ALT + up", hl.dsp.exec_cmd("~/script/gamma.sh up"))
hl.bind(mainMod .. " + ALT + down", hl.dsp.exec_cmd("~/script/gamma.sh down"))

-- wallpaper
-- bindsym $mod+Shift+w exec ~/script/swaybg.sh
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("~/script/swaybg.sh"))

-- bindsym $mod+Shift+minus move scratchpad
-- bindsym $mod+minus scratchpad show
hl.bind(mainMod .. " + SHIFT + minus", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + minus", hl.dsp.workspace.toggle_special("magic"))

-- bindsym $mod+1..0 workspace number $wsN
-- bindsym $mod+Shift+1..0 move container to workspace number $wsN
for i = 1, 10 do
	local key = i % 10
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- nerd-font
-- bindsym $mod+Shift+n exec cat "/home/t3chj4ck/nerdfont.txt" | rofi -dmenu -i | awk '{print $1}' | tr -d '\n' | wl-copy
hl.bind(mainMod .. " + SHIFT + N",
	hl.dsp.exec_cmd([[cat "/home/t3chj4ck/nerdfont.txt" | rofi -dmenu -i | awk '{print $1}' | tr -d '\n' | wl-copy]]))

-- bindsym $mod+Shift+r reload
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))

-- bindsym $mod+m exit
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.exit()'"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
