-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- 由 sway "config" 迁移而来的 Hyprland Lua 配置              --
-- 原文件: config (Sway 配置)                                --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = false })


---------------------
---- MY PROGRAMS ----
---------------------

-- set $mod Mod4
-- set $term foot
-- set $menu rofi -show run
local mainMod  = "SUPER"
local terminal = "foot"
local menu     = "rofi -show run"


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- gaps outer 8 / gaps inner 4
-- for_window [class="^.*"] border pixel 2
-- client.focused #ffffff #ffffff #ffffff #ffffff
hl.config({
	general = {
		gaps_in     = 4,
		gaps_out    = 8,

		border_size = 2,

		col         = {
			-- sway 的 client.focused 四个色值都是白色（无渐变），故这里用单色
			active_border   = "rgba(ffffffee)",
			inactive_border = "rgba(595959aa)", -- sway 未显式设置，沿用 hyprland 默认灰色
		},

		layout      = "dwindle", -- sway 原文件未指定布局引擎，Hyprland 默认用 dwindle
	},
})

-- bar { status_command i3status-rs ...; position top; tray_output none; colors{background=#000000} }
-- 原 sway 配置中这段是被注释掉的，Hyprland 同样不内置状态栏，
-- 需要用 waybar 等外部程序，见下方 AUTOSTART（保持"未启用"的状态，仅供参考）：
-- hl.on("hyprland.start", function()
--   hl.exec_cmd("waybar")
-- end)


-------------------
---- AUTOSTART ----
-------------------

-- exec fcitx5 &
-- exec nm-applet &
-- exec blueman-applet &
-- exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
-- exec wl-paste --type text --watch cliphist store &
-- exec wl-paste --type image --watch cliphist store &
-- exec mako &
-- exec ~/script/swaybg_startup.sh &
-- exec autotiling &
-- exec udiskie &
-- exec waybar &
-- exec v2rayN
hl.on("hyprland.start", function()
	hl.exec_cmd("fcitx5")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("mako")
	hl.exec_cmd("~/script/swaybg_startup.sh")
	hl.exec_cmd("autotiling")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("waybar")
	hl.exec_cmd("v2rayN")
end)

-- exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway XDG_MENU_PREFIX=arch-
-- XDG_CURRENT_DESKTOP 需要改成 Hyprland
hl.on("hyprland.start", function()
	hl.exec_cmd(
	"dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland XDG_MENU_PREFIX=arch-")
end)

-- exec swayidle -w \
--     timeout 600 '~/script/blur_lock.sh' \
--     before-sleep '~/script/blur_lock.sh'
-- Hyprland 生态里对应的空闲管理器是 hypridle（swayidle 理论上也能在 Hyprland 下跑，
-- 但推荐换成 hypridle）。这里保留 swayidle 命令原样迁移：
hl.on("hyprland.start", function()
	hl.exec_cmd([[swayidle -w timeout 600 '~/script/blur_lock.sh' before-sleep '~/script/blur_lock.sh']])
end)


---------------
---- INPUT ----
---------------

-- input "type:keyboard" { xkb_layout "us,ru"; xkb_options "grp:alt_space_toggle" }
-- input "type:touchpad" { tap enabled; natural_scroll enabled }
-- input "type:pointer"  { accel_profile flat; pointer_accel 0 }
hl.config({
	input = {
		kb_layout   = "us,ru",
		kb_variant  = "",
		kb_model    = "",
		kb_options  = "grp:alt_space_toggle",
		kb_rules    = "",

		sensitivity = 0, -- pointer_accel 0

		touchpad    = {
			natural_scroll = true,
			tap_to_click   = true,
		},
	},
})


---------------------
---- KEYBINDINGS ----
---------------------

-- floating_modifier $mod
-- Hyprland 没有 floating_modifier 这个通用开关，浮动窗口的拖动/缩放
-- 是通过下面单独的 mouse:272 / mouse:273 绑定实现的：
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- bindsym Print exec bash -c 'mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/$(date +%F_%H-%M-%S).png | wl-copy && notify-send "screenshot"'
hl.bind("Print",
	hl.dsp.exec_cmd(
	[[bash -c 'mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/$(date +%F_%H-%M-%S).png | wl-copy && notify-send "screenshot"']]))

-- clipboard
-- bindsym $mod+v exec cliphist list | rofi -dmenu -p "clipboard history" | cliphist decode | wl-copy
hl.bind(mainMod .. " + V",
	hl.dsp.exec_cmd([[cliphist list | rofi -dmenu -p "clipboard history" | cliphist decode | wl-copy]]))

-- bindsym $mod+q exec $term
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))

-- bindsym $mod+r exec $menu
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

-- bindsym Mod1+F4 kill
hl.bind("ALT + F4", hl.dsp.window.close())

-- bindsym $mod+left/down/up/right focus <dir>
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))

-- bindsym $mod+Shift+left/down/up/right move <dir>
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))

-- bindsym $mod+f fullscreen toggle
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())

-- bindsym $mod+h layout toggle split
hl.bind(mainMod .. " + H", hl.dsp.layout("togglesplit"))

-- bindsym $mod+e exec nautilus
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("nautilus"))

-- bindsym $mod+space floating toggle
hl.bind(mainMod .. " + space", hl.dsp.window.float({ action = "toggle" }))

-- bindsym $mod+a focus parent
-- 注: Hyprland Lua API 中"聚焦父容器"对应的具体函数名请以你所用版本的
-- wiki/自动补全为准，这里按命名习惯写出，如报错请改成实际可用的 API：
-- hl.bind(mainMod .. " + A", hl.dsp.window.focus_parent())

-- multimedia keys（音量/静音/亮度，均带 notify-send）
hl.bind("XF86AudioRaiseVolume",
	hl.dsp.exec_cmd(
	[[wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -t 1000 "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)"%"}')"]]),
	{ locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",
	hl.dsp.exec_cmd(
	[[wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -t 1000 "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)"%"}')"]]),
	{ locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",
	hl.dsp.exec_cmd(
	[[brightnessctl s 10%+ && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -t 1000 "Brightness" "$(brightnessctl -m | awk -F, '{print $4}')"]]),
	{ locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",
	hl.dsp.exec_cmd(
	[[brightnessctl s 10%- && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -t 1000 "Brightness" "$(brightnessctl -m | awk -F, '{print $4}')"]]),
	{ locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- gamma
-- bindsym $mod+Mod1+up   exec ~/script/gamma.sh up
-- bindsym $mod+Mod1+down exec ~/script/gamma.sh down
hl.bind(mainMod .. " + ALT + up", hl.dsp.exec_cmd("~/script/gamma.sh up"))
hl.bind(mainMod .. " + ALT + down", hl.dsp.exec_cmd("~/script/gamma.sh down"))

-- wallpaper
-- bindsym $mod+Shift+w exec ~/script/swaybg.sh
-- 注: swaybg 是 sway 专用壁纸工具，在 Hyprland 下一般用 hyprpaper，
-- 若脚本内部调用的是 swaybg 命令，需要自行改脚本内容，这里按"原封不动"保留调用路径：
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("~/script/swaybg.sh"))

-- set $ws1.."1" ... set $ws10.."0"  （数值和键位一一对应，无需变量）
-- bindsym $mod+Shift+minus move scratchpad
-- bindsym $mod+minus scratchpad show
hl.bind(mainMod .. " + SHIFT + minus", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + minus", hl.dsp.workspace.toggle_special("magic"))

-- bindsym $mod+1..0 workspace number $wsN
-- bindsym $mod+Shift+1..0 move container to workspace number $wsN
for i = 1, 10 do
	local key = i % 10 -- 10 映射到按键 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- nerd-font
-- bindsym $mod+Shift+n exec cat "/home/t3chj4ck/nerdfont.txt" | rofi -dmenu -i | awk '{print $1}' | tr -d '\n' | wl-copy
hl.bind(mainMod .. " + SHIFT + N",
	hl.dsp.exec_cmd([[cat "/home/t3chj4ck/nerdfont.txt" | rofi -dmenu -i | awk '{print $1}' | tr -d '\n' | wl-copy]]))

-- bindsym $mod+Shift+r reload
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))

-- bindsym $mod+m exit
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprctl dispatch exit"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- #window rule
-- sway 原文件里这部分是空的，没有定义任何窗口规则，故此处同样不添加。
