general {
    # before_sleep_cmd = swaylock -f -c 000000 --indicator-idle-visible
	before_sleep_cmd = hyprlock
}

listener {
    timeout = 600
    # on-timeout = swaylock -f -c 000000 --indicator-idle-visible
	on-timeout = hyprlock
}
