music_directory    "~/Music"       # Point to your MP3 folder
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"

audio_output {
    type    "pulse"                # Or "alsa" / "osx" (for Mac)
    name    "My MPD PulseAudio"
}

# Important for ncmpcpp visualizer
audio_output {
    type    "fifo"
    name    "my_fifo"
    path    "/tmp/mpd.fifo"
    format  "44100:16:2"
}
