--ozone-platform=wayland

--proxy-server=http://127.0.0.1:7897


--ignore-gpu-blocklist
--enable-zero-copy
--enable-features=AcceleratedVideoDecodeLinuxGL
--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL.
--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
