unbind C-b

set -g prefix `
bind ` send-prefix

# 解决 Vim 颜色丢失问题
set -g default-terminal "screen-256color"





#hotkey
bind n new-window
bind w kill-pane

bind v split-window -h
bind s split-window -v


#mouse
set -g mouse on

#count from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on


#tab background color
setw -g window-status-current-style "bg=#ffffff,fg=#000000,bold"
